development:
  adapter: mysql
  database: active_scaffold_demo_development
  host:
  username:
  password:
  port:
  sslcert:
  sslcapath:
  sslcipher:
  socket:
  sslkey:
  schema_order:
  dbfile:

test:
  adapter: mysql
  database: active_scaffold_demo_test
  host:
  username:
  password:
  port:
  sslcert:
  sslcapath:
  sslcipher:
  socket:
  sslkey:
  schema_order:
  dbfile:

production:
  adapter: mysql
  database: active_scaffold_demo
  host:
  username:
  password:
  port:
  sslcert:
  sslcapath:
  sslcipher:
  socket:
  sslkey:
  schema_order:
  dbfile:
