development:
  adapter: mysql
  database: active_scaffold_demo_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  database: active_scaffold_demo_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: active_scaffold_demo
  host: localhost
  username: root
  password:
