development:
  adapter: mysql
  database: active_scaffold_demo_development
  host: 127.0.0.1
  username: root

test:
  adapter: mysql
  database: active_scaffold_demo_test
  host: 127.0.0.1
  username: root
  password: root

production:
  adapter: mysql
  database: active_scaffold_demo
  host: 127.0.0.1
  username: root
  password: root
