# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "alphas", :force => true do |t|
    t.column "name",         :string
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "meta_title",   :string
    t.column "meta_keyword", :string
  end

  create_table "alphas_deltas", :id => false, :force => true do |t|
    t.column "alpha_id", :integer, :null => false
    t.column "delta_id", :integer, :null => false
  end

  create_table "betas", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "alpha_id",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "deltas", :force => true do |t|
    t.column "title",      :string,   :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "epsilons", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "gamma_id",   :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "gammas", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "alpha_id",   :integer,  :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "zetas", :force => true do |t|
    t.column "name",       :string,   :null => false
    t.column "gamma_id",   :integer,  :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

end
